intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
import intf_libs += libcrails%lib{crails}
import intf_libs += libcrails-design-patterns%lib{crails-design-patterns}
import intf_libs += libcrails-database-url%lib{crails-database-url}

lib{crails-databases}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{export}@./: cxx.importable = false

cxx.poptions =+  "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_SHARED_BUILD

lib{crails-databases}:
{
  cxx.export.poptions = "-I$out_root/libcrails-databases/" "-I$src_root/libcrails-databases/"
  cxx.export.libs = $intf_libs
}

liba{crails-databases}: cxx.export.poptions += -DLIBCRAILS_STATIC
libs{crails-databases}: cxx.export.poptions += -DLIBCRAILS_SHARED

if $version.pre_release
  lib{crails-databases}: bin.lib.version = "-$version.project_id"
else
  lib{crails-databases}: bin.lib.version = "-$version.major.$version.minor"

{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
